package rouy

const (
	CT_XML  = "text/xml"
	CT_HTML = "text/html"
	CT_TXT  = "text/plain"
	CT_AXML = "application/xml"
	CT_JSON = "application/json"
	CT_JS   = "application/javascript"
	CT_CSS  = "application/css"
	CT_ZIP  = "application/zip"
	CT_PDF  = "application/pdf"
	CT_CSV  = "application/csv"
	CT_AF   = "application/x-www-form-urlencoded"
	CT_OS   = "application/oct_et-stream"
	CT_FD   = "multipart/form-data"
	CT_PNG  = "image/png"
	CT_JPEG = "image/jpeg"
	CT_GIF  = "image/gif"
	CT_BMP  = "image/bmp"
	CT_WEBP = "image/webp"
	CT_SVG  = "image/svg+xml"
	CT_AVI  = "video/avi"
	CT_MP4  = "video/mp4"
	CT_WEBM = "video/webm"
	CT_MKV  = "video/x-matroska"
	CT_MP3  = "audio/mpeg"
	CT_WAV  = "audio/x-wav"
	CT_FLV  = "video/x-flv"
	CT_FLAC = "audio/x-flac"

	CT_XMLUTF8   = "text/xml; charset=utf-8"
	CT_HTMLUTF8  = "text/html; charset=utf-8"
	CT_TXTUTF8   = "text/plain; charset=utf-8"
	CT_AXMLUTF8  = "application/xml; charset=utf-8"
	CT_JSONUTF8  = "application/json; charset=utf-8"
	CT_CSSONUTF8 = "application/css; charset=utf-8"
	CT_ZIPONUTF8 = "application/zip; charset=utf-8"
	CT_PDFONUTF8 = "application/pdf; charset=utf-8"
	CT_CSVONUTF8 = "application/csv; charset=utf-8"
	CT_JSUTF8    = "application/javascript; charset=utf-8"
)
